package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminid;
     private String name;
     private String email;
     private String password;
     private String responsibility;
     private int active;

    public Admin() {
    }

    public Admin(String name, String email, String password, String responsibility, int active) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.responsibility = responsibility;
       this.active = active;
    }
   
    public Integer getAdminid() {
        return this.adminid;
    }
    
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getResponsibility() {
        return this.responsibility;
    }
    
    public void setResponsibility(String responsibility) {
        this.responsibility = responsibility;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


