package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private String id;
     private String fname;
     private String lname;
     private String email;
     private String phoneNumber;
     private Date eventDate;
     private String eventStartTime;
     private String eventStopTime;
     private String hallNumber;
     private double payableAmount;
     private String paymentConfirmation;
     private String checkedby;
     private String paymentMethod;

    public Event() {
    }

    public Event(String id, String fname, String lname, String email, String phoneNumber, Date eventDate, String eventStartTime, String eventStopTime, String hallNumber, double payableAmount, String paymentConfirmation, String checkedby, String paymentMethod) {
       this.id = id;
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.eventDate = eventDate;
       this.eventStartTime = eventStartTime;
       this.eventStopTime = eventStopTime;
       this.hallNumber = hallNumber;
       this.payableAmount = payableAmount;
       this.paymentConfirmation = paymentConfirmation;
       this.checkedby = checkedby;
       this.paymentMethod = paymentMethod;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    public String getEventStartTime() {
        return this.eventStartTime;
    }
    
    public void setEventStartTime(String eventStartTime) {
        this.eventStartTime = eventStartTime;
    }
    public String getEventStopTime() {
        return this.eventStopTime;
    }
    
    public void setEventStopTime(String eventStopTime) {
        this.eventStopTime = eventStopTime;
    }
    public String getHallNumber() {
        return this.hallNumber;
    }
    
    public void setHallNumber(String hallNumber) {
        this.hallNumber = hallNumber;
    }
    public double getPayableAmount() {
        return this.payableAmount;
    }
    
    public void setPayableAmount(double payableAmount) {
        this.payableAmount = payableAmount;
    }
    public String getPaymentConfirmation() {
        return this.paymentConfirmation;
    }
    
    public void setPaymentConfirmation(String paymentConfirmation) {
        this.paymentConfirmation = paymentConfirmation;
    }
    public String getCheckedby() {
        return this.checkedby;
    }
    
    public void setCheckedby(String checkedby) {
        this.checkedby = checkedby;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }




}


