package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1



/**
 * GenerateDiscount generated by hbm2java
 */
public class GenerateDiscount  implements java.io.Serializable {


     private String discountCode;
     private int discountAmount;
     private int reason;
     private String status;

    public GenerateDiscount() {
    }

    public GenerateDiscount(String discountCode, int discountAmount, int reason, String status) {
       this.discountCode = discountCode;
       this.discountAmount = discountAmount;
       this.reason = reason;
       this.status = status;
    }
   
    public String getDiscountCode() {
        return this.discountCode;
    }
    
    public void setDiscountCode(String discountCode) {
        this.discountCode = discountCode;
    }
    public int getDiscountAmount() {
        return this.discountAmount;
    }
    
    public void setDiscountAmount(int discountAmount) {
        this.discountAmount = discountAmount;
    }
    public int getReason() {
        return this.reason;
    }
    
    public void setReason(int reason) {
        this.reason = reason;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


