package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private String messageid;
     private String email;
     private String messagetitle;
     private String messagebody;

    public Messages() {
    }

    public Messages(String messageid, String email, String messagetitle, String messagebody) {
       this.messageid = messageid;
       this.email = email;
       this.messagetitle = messagetitle;
       this.messagebody = messagebody;
    }
   
    public String getMessageid() {
        return this.messageid;
    }
    
    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMessagetitle() {
        return this.messagetitle;
    }
    
    public void setMessagetitle(String messagetitle) {
        this.messagetitle = messagetitle;
    }
    public String getMessagebody() {
        return this.messagebody;
    }
    
    public void setMessagebody(String messagebody) {
        this.messagebody = messagebody;
    }




}


