package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Newemployee generated by hbm2java
 */
public class Newemployee  implements java.io.Serializable {


     private Integer employeeid;
     private String firstname;
     private String lastname;
     private String email;
     private String phonenumber;
     private String address;
     private Date dob;
     private String gender;
     private String nextofkin;
     private String nextofkinphone;
     private String department;
     private Date approvaldate;
     private String addedby;

    public Newemployee() {
    }

    public Newemployee(String firstname, String lastname, String email, String phonenumber, String address, Date dob, String gender, String nextofkin, String nextofkinphone, String department, Date approvaldate, String addedby) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.phonenumber = phonenumber;
       this.address = address;
       this.dob = dob;
       this.gender = gender;
       this.nextofkin = nextofkin;
       this.nextofkinphone = nextofkinphone;
       this.department = department;
       this.approvaldate = approvaldate;
       this.addedby = addedby;
    }
   
    public Integer getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNextofkin() {
        return this.nextofkin;
    }
    
    public void setNextofkin(String nextofkin) {
        this.nextofkin = nextofkin;
    }
    public String getNextofkinphone() {
        return this.nextofkinphone;
    }
    
    public void setNextofkinphone(String nextofkinphone) {
        this.nextofkinphone = nextofkinphone;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public Date getApprovaldate() {
        return this.approvaldate;
    }
    
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }
    public String getAddedby() {
        return this.addedby;
    }
    
    public void setAddedby(String addedby) {
        this.addedby = addedby;
    }




}


