package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OtherExpenses generated by hbm2java
 */
public class OtherExpenses  implements java.io.Serializable {


     private Integer id;
     private String expensesOn;
     private double amount;
     private Date date;

    public OtherExpenses() {
    }

    public OtherExpenses(String expensesOn, double amount, Date date) {
       this.expensesOn = expensesOn;
       this.amount = amount;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getExpensesOn() {
        return this.expensesOn;
    }
    
    public void setExpensesOn(String expensesOn) {
        this.expensesOn = expensesOn;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


