package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private String id;
     private String fname;
     private String lname;
     private String email;
     private String phonenumber;
     private Date checkInDate;
     private String checkInTime;
     private Date checkOutDate;
     private String checkOutTime;
     private String medicalCondition;
     private double payableAmount;
     private String roomCategory;
     private String roomPosition;
     private String roomNumber;
     private String paymentStatus;
     private String checkedby;
     private String paymentMethod;

    public Reservation() {
    }

    public Reservation(String id, String fname, String lname, String email, String phonenumber, Date checkInDate, String checkInTime, Date checkOutDate, String checkOutTime, String medicalCondition, double payableAmount, String roomCategory, String roomPosition, String roomNumber, String paymentStatus, String checkedby, String paymentMethod) {
       this.id = id;
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.phonenumber = phonenumber;
       this.checkInDate = checkInDate;
       this.checkInTime = checkInTime;
       this.checkOutDate = checkOutDate;
       this.checkOutTime = checkOutTime;
       this.medicalCondition = medicalCondition;
       this.payableAmount = payableAmount;
       this.roomCategory = roomCategory;
       this.roomPosition = roomPosition;
       this.roomNumber = roomNumber;
       this.paymentStatus = paymentStatus;
       this.checkedby = checkedby;
       this.paymentMethod = paymentMethod;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public Date getCheckInDate() {
        return this.checkInDate;
    }
    
    public void setCheckInDate(Date checkInDate) {
        this.checkInDate = checkInDate;
    }
    public String getCheckInTime() {
        return this.checkInTime;
    }
    
    public void setCheckInTime(String checkInTime) {
        this.checkInTime = checkInTime;
    }
    public Date getCheckOutDate() {
        return this.checkOutDate;
    }
    
    public void setCheckOutDate(Date checkOutDate) {
        this.checkOutDate = checkOutDate;
    }
    public String getCheckOutTime() {
        return this.checkOutTime;
    }
    
    public void setCheckOutTime(String checkOutTime) {
        this.checkOutTime = checkOutTime;
    }
    public String getMedicalCondition() {
        return this.medicalCondition;
    }
    
    public void setMedicalCondition(String medicalCondition) {
        this.medicalCondition = medicalCondition;
    }
    public double getPayableAmount() {
        return this.payableAmount;
    }
    
    public void setPayableAmount(double payableAmount) {
        this.payableAmount = payableAmount;
    }
    public String getRoomCategory() {
        return this.roomCategory;
    }
    
    public void setRoomCategory(String roomCategory) {
        this.roomCategory = roomCategory;
    }
    public String getRoomPosition() {
        return this.roomPosition;
    }
    
    public void setRoomPosition(String roomPosition) {
        this.roomPosition = roomPosition;
    }
    public String getRoomNumber() {
        return this.roomNumber;
    }
    
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public String getCheckedby() {
        return this.checkedby;
    }
    
    public void setCheckedby(String checkedby) {
        this.checkedby = checkedby;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }




}


