package com.bean;
// Generated Mar 19, 2019 12:41:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserData generated by hbm2java
 */
public class UserData  implements java.io.Serializable {


     private String userid;
     private String name;
     private String email;
     private String phonenumber;
     private String address;
     private String gender;
     private String nextofkin;
     private String nextofkinphone;
     private String password;
     private Date registerdate;
     private String hash;
     private int active;

    public UserData() {
    }

    public UserData(String userid, String name, String email, String phonenumber, String address, String gender, String nextofkin, String nextofkinphone, String password, Date registerdate, String hash, int active) {
       this.userid = userid;
       this.name = name;
       this.email = email;
       this.phonenumber = phonenumber;
       this.address = address;
       this.gender = gender;
       this.nextofkin = nextofkin;
       this.nextofkinphone = nextofkinphone;
       this.password = password;
       this.registerdate = registerdate;
       this.hash = hash;
       this.active = active;
    }
   
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNextofkin() {
        return this.nextofkin;
    }
    
    public void setNextofkin(String nextofkin) {
        this.nextofkin = nextofkin;
    }
    public String getNextofkinphone() {
        return this.nextofkinphone;
    }
    
    public void setNextofkinphone(String nextofkinphone) {
        this.nextofkinphone = nextofkinphone;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }




}


